spring:
  application:
    name: csv-processor
  threads:
    virtual:
      enabled: true
  ai:
    dashscope:
      chat:
        options:
          model: qwen-plus
          temperature: 0.1
io:
  github:
    llmagentbuilder:
      chatagent:
        name: CSV Processor
        description: Process CSV files
        usageInstruction: What you want to do with the CSV file?
        reActJson:
          systemInstructions: |
            Process CSV files.
        memory:
          enabled: false
        tools:
          config:
            readLocalFile:
              basePath: test_data/input
            writeLocalFile:
              basePath: test_data/output
            executePythonCode:
              workingDirectory: test_data/input